### ISSUE TITLE
CI and tests for the stubs

### ISSUE THREAD

**Issue by JukkaL** [JelleZijlstra/sqlalchemy-stubs#1]
These stubs are sufficiently complicated that perhaps it would make sense to have tests that exercise stub functionality, as discussed in https://github.com/python/typeshed/issues/754. If these were run as part of a travis CI job, they would hopefully catch some regressions.

Here is an idea for how to do this in a simple fashion:

* Write a bunch of small annotated programs that use core SQLAlchemy functionality. 
* Tests would type check the programs using a pinned version of mypy and verify that there are no errors.
* As issues in the stubs are fixed, add new test programs that previously generated false positives.

These should at least prevent the sorts of major regressions that we used to have when the stubs lived in typeshed.

**Comment by JelleZijlstra** [comment]
Yes, that will be useful, and it might also be a good way to explore ways we can later integrate such tests in typeshed itself (the last attempt, python/typeshed#917, was rejected).

Would it be possible to use `.test` files here like mypy itself uses? That would give us a pretty nice framework for writing tests.

**Comment by JelleZijlstra** [comment]
Superseded by Dropbox's own set of stubs.
