### ISSUE TITLE
How about https://github.com/dropbox/sqlalchemy-stubs?

### ISSUE THREAD

**Issue by gvanrossum** [JelleZijlstra/sqlalchemy-stubs#10]
There's a more recent set of stubs in https://github.com/dropbox/sqlalchemy-stubs -- is there any relationship between the two? If the latter is the recommended set, should this set be deprecated?

**Comment by JelleZijlstra** [comment]
Yes, let's deprecate this one. @ilevkivskyi asked me a while ago about improving this repo, but I guess he ended up using a different repo.

**Comment by ilevkivskyi** [comment]
I used these stubs as a starting point, but yes, we decided it is simpler to put the stubs repo in Dropbox org.

**Comment by JelleZijlstra** [comment]
I just added a note in the README (https://github.com/JelleZijlstra/sqlalchemy-stubs/commit/a6b8f9740f7aeb441e1f17c261c35292937435ab) and I'll now archive the repo, which I understand makes it read-only but preserves the code as a historical record.
